### ISSUE TITLE
/f funny chat glitch

### ISSUE THREAD

**Issue by Smith-sonite** [NebulaMC-GG/Support#1515] opened 2022-06-25 15:20 UTC
title says it all

![2022-06-25_08 21 10](https://user-images.githubusercontent.com/107899014/175780026-cab21db4-1fa8-4e43-8506-aa33dc4a32ae.png)

**Comment by HackuJacku** [comment] 2022-06-27 23:48
This is a duplicate of #1536, please refer to this

**Closed by HackuJacku** 2022-06-27 23:48 UTC
Labels: bug, nebulamc
