### ISSUE TITLE
/buy store goal reward not being given out

### ISSUE THREAD

**Issue by lexjo** [NebulaMC-GG/Support#1447] opened 2022-06-15 15:49 UTC
![image](https://user-images.githubusercontent.com/17412315/173870698-e0fe39fa-c4a6-4f6e-8f83-9b30e7a41f90.png)
Just now this message popped up in chat on Orion and no solar crate keys were given

**Comment by HackuJacku** [comment] 2022-06-28 00:13
This is a duplicate of #1523. Please refer to this issue but thank you for the report :)

**Closed by HackuJacku** 2022-06-28 00:13 UTC
Labels: atlantis, review
