### ISSUE TITLE
Galaxy ball hunt issue

### ISSUE THREAD

**Issue by Goeategg** [NebulaMC-GG/Support#1277] opened 2022-06-04 10:49 UTC
While I was hunting for the galaxy balls I found one that whenever I click on it it says “Owner: unknown” this bugged ball is at X:-38 Y:79 Z:50

**Comment by Rasgnarok** [comment] 2022-06-04 14:18
Duplicate of https://github.com/NebulaMC-GG/Support/issues/1273 - or are they different heads @ Hacko

**Comment by starwarschamp4** [comment] 2022-06-04 21:24
Same head, original ticket is [#1266 ](https://github.com/NebulaMC-GG/Support/issues/1266)

**Comment by Rasgnarok** [comment] 2022-08-06 19:03
Closing, duplicate.

**Closed by Rasgnarok** 2022-08-06 19:03 UTC
Labels: bug, spigot
