### ISSUE TITLE
Mball Head in Hub

### ISSUE THREAD

**Issue by ColTheFurret** [NebulaMC-GG/Support#1273] opened 2022-06-04 06:54 UTC
So Before the Orion thing, I went to do a bit of the Ball Hunting to try to get the tag, and when I found this one, I didn't get given the thing in chat saying I found it, rather a text at the bottom that says "Unknown Owner" instead, not counting to the total count.
Tried to keep it vague in case others peek in.
![Mball Spot](https://user-images.githubusercontent.com/83987372/171988335-086f9249-d764-4490-99ff-c7b4e6dba3be.png)

**Comment by HackuJacku** [comment] 2022-08-07 13:51
Duplicate of #1266, please look there for update

**Closed by HackuJacku** 2022-08-07 13:51 UTC
Labels: bug, spigot
