### ISSUE TITLE
Solar Crate Icon Issue

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [NebulaMC-GG/Support#1702] opened 2022-08-02 13:39 UTC
It displayed it would give me a form modifier, when the animation ended it gave me a growth modifier. Needs further testing.

**Comment by HackuJacku** [comment] 2022-08-05 16:49
Unable to reproduce, assuming it's the issue of another player 'stealing' off you whilst opening the crate - fixed in an upcoming update.

**Closed by HackuJacku** 2022-08-05 16:49 UTC
