### ISSUE TITLE
Shaymin unable to move relearn

### ISSUE THREAD

**Issue by LimitlessJoker** [NebulaMC-GG/Support#1524] opened 2022-06-27 00:21 UTC
Due to the fact the spawn is constant night time I can't have the shaymin sky form relearn it's moves due to it constantly being night time. As the Gracidea flower is only useable during daytime.

IGN: LimitlessJoker

**Comment by Menno165** [comment] 2022-07-12 22:45
Closing as it is an duplicate of #1516

**Closed** 2022-08-05 20:46 UTC
Labels: bug, pixelmon
