### ISSUE TITLE
[EggTimer] double message.

### ISSUE THREAD

**Issue by Vohras2** [NebulaMC-GG/Support#473] opened 2020-04-08 10:40 UTC
Egg timer has a double message on the 4minute 30 second left mark.

[https://imgur.com/XYzs71D](url)

**Comment by Hiroku** [comment] 2020-07-15 13:05
This should now be fixed, please retest if it's reproducible

**Comment by Vohras2** [comment] 2020-09-27 00:34
Issue is still ongoing.
https://imgur.com/q4rVji6

**Comment by Rasgnarok** [comment] 2021-01-13 23:39
@Vohras2 Does this still happen?

**Comment by Vohras2** [comment] 2021-01-13 23:41
Yes, it does.

**Comment by Rasgnarok** [comment] 2021-01-14 00:14
Closing, as we can't reproduce. Must be an edge case. We would need to know what Pokemon was hatched.

**Comment by Vohras2** [comment] 2021-01-31 04:59
Just happened to me again when I was hatching a bunnelby.

**Comment by Vohras2** [comment] 2021-05-27 05:41
Just happened once again on hatching Sableye and Mantine eggs.

**Comment by Hiroku** [comment] 2021-06-06 11:59
After looking into this again, it's actually really bizarre and should be impossible if Pixelmon is doing a good job of this. Unsure if I'm going to be able to fix it

**Comment by Rasgnarok** [comment] 2022-06-02 03:26
Closing, this will need re-testing on 1.16.5.

**Closed by Rasgnarok** 2022-06-02 03:26 UTC
Labels: bug, needs testing, nebulamc
